# Generated by Django 3.1.7 on 2021-03-14 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restbuck_app', '0006_delete_productorderfeaturevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='title',
            field=models.CharField(help_text="A display title for one product's feature", max_length=255),
        ),
        migrations.AlterField(
            model_name='featuresvalue',
            name='title',
            field=models.CharField(help_text='display title for an option of feature', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.IntegerField(help_text='cost of product'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='feature_list',
        ),
        migrations.AddField(
            model_name='product',
            name='feature_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='restbuck_app.feature'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='display title for a product', max_length=255),
        ),
    ]
