# Generated by Django 3.1.7 on 2021-03-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restbuck_app', '0007_auto_20210314_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='feature_list',
            new_name='feature',
        ),
    ]
