# Generated by Django 3.1.7 on 2021-03-14 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restbuck_app', '0008_auto_20210314_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_list',
            field=models.ManyToManyField(help_text='list of products client ordered', related_name='products', through='restbuck_app.ProductOrder', to='restbuck_app.Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'waiting'), (1, 'preparation'), (2, 'ready'), (3, 'delivered'), (4, 'canceled')], default=0, help_text='state of order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(help_text='client', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='count',
            field=models.IntegerField(help_text='number of product client ordered'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='feature_value',
            field=models.ForeignKey(help_text='ordered option of product', on_delete=django.db.models.deletion.PROTECT, to='restbuck_app.featuresvalue'),
        ),
        migrations.DeleteModel(
            name='ProductFeature',
        ),
    ]
