# Generated by Django 3.1.7 on 2021-03-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restbuck_app', '0009_auto_20210314_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='state',
        ),
        migrations.AddField(
            model_name='order',
            name='previous_state',
            field=models.SmallIntegerField(choices=[(0, 'waiting'), (1, 'preparation'), (2, 'ready'), (3, 'delivered'), (4, 'canceled')], default=0, help_text='previous state of order'),
        ),
    ]
