# Generated by Django 3.1.7 on 2021-03-18 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restbuck_app', '0012_auto_20210318_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='feature_value',
            field=models.ForeignKey(blank=True, help_text='ordered option of product', null=True, on_delete=django.db.models.deletion.PROTECT, to='restbuck_app.featuresvalue'),
        ),
    ]
